### ISSUE TITLE
Mockups: Sign up / Sign in

### ISSUE THREAD

**Issue by yaseminalpay** [SWEZenith/Fall2017Swe574-Zenith#13]
Create mockups for user sign up and user sign in for web app and android app
The mockup will help to finalize the following requirement:

> 1. User Account Operations
> 1.1. User shall be able to provide their username, email and password while creating a new account.
> 1.2. User shall be able to login to their account using username and password.
> 1.3. User shall be able to update their username and password.
> 1.4. User shall be able to reset their password by using their email address.
>

**Comment by yesimoral** [comment]
1.3. User shall be able to update their username and password.
This is missing from the sign up/sign in mock ups now. I think we should put this functionality to some other page.
