### ISSUE TITLE
Mockups: Searching Content

### ISSUE THREAD

**Issue by yaseminalpay** [SWEZenith/Fall2017Swe574-Zenith#14]
Create mockups for searching content for web app and android app:
Issue no #9 and #10 may give a hint.
The mockup will help to finalize the following requirements:

> 5. Displaying Content
> 
> 5.1. User shall be able to display content in the home page.
> 5.2. User shall be able to have a portfolio page where he can see all the content and annotations he has created.
> 5.3. The system shall be able to display the contents with their attributes and annotations that have been created. 
> 
> 6. Searching Content
> 6.1. User shall be able to search content by content attributes.
>

**Comment by kahyabatuhan** [comment]
Search content embeded in the Home page with Advanced Seach (pop-up) link
