### ISSUE TITLE
IRI Research for Content Annotation

### ISSUE THREAD

**Issue by yaseminalpay** [SWEZenith/Fall2017Swe574-Zenith#19]
Research about how to identify the resources (annotation targets/contents) with IRI

**Comment by gokceyucel** [comment]
from https://www.w3.org/TR/annotation-model/
> IRI
An IRI, or Internationalized Resource Identifier, is an extension to the URI specification to allow characters from Unicode, whereas URIs must be made up of a subset of ASCII characters. There is a mapping algorithm for translating between IRIs and the equivalent encoded URI form. IRIs are defined by [rfc3987].


Term | Type | Description
-- | -- | --
id | Property | The IRI that identifies the Body or Target resource. Bodies or Targets which are External Web Resources must have exactly 1 id with the value of the resource's IRI, and that IRI may have a fragment component.


```
EXAMPLE 4: IRIs with Fragment Components
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno4",
  "type": "Annotation",
  "body": "http://example.org/description1",
  "target": {
    "id": "http://example.com/image1#xywh=100,100,300,300",
    "type": "Image",
    "format": "image/jpeg"
  }
}
```
