### ISSUE TITLE
GitHub Functionality Practices

### ISSUE THREAD

**Issue by pinarersoy** [SWEZenith/Fall2017Swe574-Zenith#26]
- How to fork repository
- How to to create pull request

**Sample Links:**

**Fork a Repo:** https://help.github.com/articles/fork-a-repo/
**Creating a Pull Request:** https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by bulentrahimkazanci** [comment]
In addition to links given above, the video on the following link can be watched to see whole process in action.

https://www.youtube.com/watch?v=_NrSWLQsDL4

**Comment by gokceyucel** [comment]
In our API repository (https://github.com/SWEZenith/Living-History-API) I have protected `master` branch to avoid pushing/force pushing code to it. Instead, a feature should be developed in a separate branch then it should be merged with `master` by opening a `pull request`.

**Comment by bulentrahimkazanci** [comment]
After last week, I think how to use vcs is crystal clear so I close this issue.
