### ISSUE TITLE
Store / Retrieve Annotations & API Usage

### ISSUE THREAD

**Issue by pinarersoy** [SWEZenith/Fall2017Swe574-Zenith#27]
How to store & retrieve annotations including API? 

**Sample Links:** 

- http://docs.annotatorjs.org/en/latest/modules/storage.html
- http://docs.annotatorjs.org/en/v1.2.x/plugins/store.html
- https://github.com/swagger-api/swagger-core/wiki/annotations

**Comment by gokceyucel** [comment]
https://github.com/SWEZenith/Living-History-API

Annotations could be stored and retrieved through the api. However we haven't fully implemented the ldp protocol. For now, it's just working with plain json objects.

**Comment by gokceyucel** [comment]
I re-open this issue since we haven't implemented ldp protocol yet.
