### ISSUE TITLE
API design 

### ISSUE THREAD

**Issue by yaseminalpay** [SWEZenith/Fall2017Swe574-Zenith#33]
All APIs in the system with:
-Request - response
-URL structure
 for: 
Create User
Get User
Create Content
Get Content
Create Annotation
Get Annotation

note:

- [ ] add RETRIEVE ANNOTATION BY CONTENT(TARGET) ID
- [ ] add define target id
- [ ] finalize query content endpoint

**Comment by yaseminalpay** [comment]
initial one is added to wiki: https://github.com/SWEZenith/Living-History-API/wiki/API-Doc

Discussions:

- [x] Do you have any recommendations for advanced search? refer to retrieve content by query in here:
 https://github.com/SWEZenith/Living-History-API/wiki/content-controller

- [x] how the user dto should look like? i have some concerns about it about passwords in GET request -> https://github.com/SWEZenith/Living-History-API/wiki/user-controller
 
- [x] @gokceyucel I am not sure how we should store "creator" in annotation controller. i think we can do it like this:         "creator": "http://example.net/api/v1/users/yasemin". what do you think?

- [ ] also @gokceyucel, maybe we should target the content like this when posting annotation:
"id": "http://example.com/contents/1#description#xywh=100,100,300,300"
not sure if this is possible though. what do you think? 
i have found some examples here: https://github.com/SWE574-Groupago/heritago/wiki/7.-REST-API

**Comment by bulentrahimkazanci** [comment]
Hey Yasemin,

1- What do you mean by recommendations like how to retrieve data through mongoDB?
2- Do we really need end-points returning all users on db and users info? I thought that only registration is sufficient for that controller but if you have other concerns please enlighten me :)
3- Seems appropriate for me 👍 
4- I think there can be more than one annotations having same id in this case. Two user may annotate same areas on an image essentially. Is the id property ambiguous point here?

**Comment by yaseminalpay** [comment]
1-i was thinking about how we should query the contents. like if we should POST with search DTO or just in query params.. etc. anyway, i think it's ok this way.
2- you are right, we don't need it. it's just a habit :) i will delete "get all users". 
3-ok
4-sorry, what i was talking about is id inside target (target id)- should disc
