### ISSUE TITLE
Home page listview content implementation

### ISSUE THREAD

**Issue by gokceyucel** [SWEZenith/Fall2017Swe574-Zenith#62]
- If content's cover_image is null, a placeholder image should be displayed.
- Pull to refresh should be implemented

**Comment by bulentrahimkazanci** [comment]
Those are nice examples may inspire us

- https://dribbble.com/shots/3061593-List-View-for-Coupon-App
- https://dribbble.com/shots/2722475-Product-Listing-Furlenco
- https://dribbble.com/shots/1605810-NY-List-View
