### ISSUE TITLE
Date format bug on client

### ISSUE THREAD

**Issue by bulentrahimkazanci** [SWEZenith/Fall2017Swe574-Zenith#67]
User shall be able to add generic types for date field. Followings are example for date field.

- 21.01.2010
- 01.2010
- 2010
- 90s
- end of 80s

**Comment by gokceyucel** [comment]
This is resolved ind https://github.com/SWEZenith/Living-History-API/commit/4ec48fc0c1294c9d822845bbf3c2c36310900527
