### ISSUE TITLE
Requirement Review & Elicitation Questions

### ISSUE THREAD

**Issue by yaseminalpay** [SWEZenith/Fall2017Swe574-Zenith#8]
Review the requirement document and raise eliciation questions if there is any.

Requirement document is in google docs:
https://docs.google.com/document/d/1-YVfCIP_d5RH30GCSzcshNRFYqnQaLMRvkbKYz695gM/edit?usp=sharing

**Comment by yaseminalpay** [comment]
Slack test

**Comment by bulentrahimkazanci** [comment]
rewrite requirements as markdown style on wiki page.
